### ISSUE TITLE
Adding Context Plugin Panics

### ISSUE THREAD

**Issue by njt1968** [StarArawn/kayak_ui#190]
I am trying to go through the book to learn Kayak, but even the first example copy pasted directly crashes at runtime. Even something as simple as this crashes:

![image](https://user-images.githubusercontent.com/113371844/206058303-05ecb14d-16d5-4118-9500-a83a851a4f3a.png)

![image](https://user-images.githubusercontent.com/113371844/206058562-90ace9d9-dc4b-4ae3-9e78-2b90d415583f.png)

Not sure how to proceed and I can't find any questions/previous issues about this.

Also, the book's first example has this line:
![image](https://user-images.githubusercontent.com/113371844/206058712-0e1999de-2c6f-4e92-8846-bf949659ad1a.png)
but in my program the UICameraBundle constructor doesn't take any arguments.

Any help would be appreciated TY

**Comment by StarArawn** [comment]
A lot of work has gone in since the 0.1 release. This issue looks like it is caused by something that was already fixed. 

> Also, the book's first example has this line:
> but in my program the UICameraBundle constructor doesn't take any arguments.
This is because main has a lot of changes. You can view the 0.1 book/examples here:
https://github.com/StarArawn/kayak_ui/tree/v0.1.0
And a full list of releases here:
https://github.com/StarArawn/kayak_ui/releases

If you would like to switch to the main branch I recommend the following cargo settings:
`kayak_ui = { git="https://github.com/StarArawn/kayak_ui/", rev="66b8dcda0272f1bf74ac2fbcfbf00d3bd68952e7" }`

If you still have any problems please feel free to open a new issue!
