### ISSUE TITLE
Change Cursor

### ISSUE THREAD

**Issue by StarArawn** [StarArawn/kayak_ui#6]
Right now bevy doesn't expose winit's `set_cursor_icon` function. We need to enable that functionality in bevy to show different cursors. Then we can hook into the events to change the cursor icon.

**Comment by MrGVSV** [comment]
Created a PR on Bevy ([#3395](https://github.com/bevyengine/bevy/pull/3395)) that should unblock this.

**Comment by MrGVSV** [comment]
Also, how might this work? Ideally each widget could specify its own `cursor` in `Style`, right? But so far— apart from rendering— it seems like most Bevy stuff is one-way (i.e., `process_events`).

Would we add a command buffer system (à la `bevy_window`'s [`WindowCommand`](https://github.com/bevyengine/bevy/blob/340957994dc2c85f7a3ebc5ea6a5ad1b161e0041/crates/bevy_window/src/window.rs#L138-L183))? Or is there a better way of handling this?

**Comment by StarArawn** [comment]
> Also, how might this work? Ideally each widget could specify its own `cursor` in `Style`, right? But so far— apart from rendering— it seems like most Bevy stuff is one-way (i.e., `process_events`).
> 
> Would we add a command buffer system (à la `bevy_window`'s [`WindowCommand`](https://github.com/bevyengine/bevy/blob/340957994dc2c85f7a3ebc5ea6a5ad1b161e0041/crates/bevy_window/src/window.rs#L138-L183))? Or is there a better way of handling this?

Not sure yet. I'll give it some thought!

**Comment by MrGVSV** [comment]
~~Another idea would be to add an associated type on `KayakContext`. Then the `BevyContext` can designate `World` as the type. Since rendering is an exclusive system anyways, we can just pass the `World` to `context.update(...)`.~~

Although, now that I think about it, that might not work as easily as I thought since `KayakContext` would need to be a trait and the `Widget` would need to change its render method to something like `fn render(&mut self, context: Box<&mut dyn KayakContextTrait>)`.

Hm... 🤔

**Comment by StarArawn** [comment]
I think we have a current_cursor on context that bevy_kayak can access? We then check styles to see what the cursor should be when hovering over a widget. It seems like this should be straightforward to implement now. 🤔

**Comment by MrGVSV** [comment]
> I think we have a current_cursor on context that bevy_kayak can access? We then check styles to see what the cursor should be when hovering over a widget. It seems like this should be straightforward to implement now. 🤔 

Yeah should be able to set it on mouse in.
