### ISSUE TITLE
Spinbox Widget

### ISSUE THREAD

**Issue by Ygg01** [StarArawn/kayak_ui#93]
# What are spinboxes?

Spinbox is a number-only `TextBox` with a special `+`/`-` or `<`/`>` near it. Some examples:

QT Spinbox
![firefox_fGY6qqvzan](https://user-images.githubusercontent.com/1146204/160247139-e6de144a-1b89-408d-9ab0-d6b236bc92e1.png)

Caves of Qud character creation
![CoQ_znbstOTZFH](https://user-images.githubusercontent.com/1146204/160247322-8bd4bb75-1ca9-4d35-b4d2-7f9f55887340.png)

# Why use them?

They are ubiquitous, and they are needed in various places like character creation and UI elements that usually want small changes based on increment/decrement.

# Design considerations 

- Some way to customize increment decrement chars
- Perhaps some way to define how buttons can be placed grouped some small mockup I made
![Aseprite_Td5jPYUaG8](https://user-images.githubusercontent.com/1146204/160248210-c443f454-91c2-49ec-8b83-44b02c6f0f8f.png)
- Ways to validate the values and prevent change; like for example, attributes can't go below ten or over twenty

**Comment by MrGVSV** [comment]
This would be a really great addition. And I think all your variants look good (although I'd personally put `+` on the right instead of the left) and useful— especially with automatic validation handling.

I think another thing (that maybe goes without saying), the text itself should be editable like a textbox.
